source 'http://rubygems.org'

gem 'SystemTimer'
gem 'crack'
gem 'daemons'
gem 'data_objects'
gem 'dm-aggregates'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-mysql-adapter'
gem 'dm-pager'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-transactions'
gem 'dm-validations'
gem 'dwc-archive'
gem 'escape'
gem 'fastercsv'
gem 'grit'
gem 'haml'
gem 'json'
gem 'nokogiri'
gem 'optiflag'
gem 'parsley-store'
gem 'rack-test'
gem 'rails'
gem 'resque'
gem 'rest-client'
gem 'rspec'
gem 'ruby-debug'
gem 'sinatra'
gem 'will_paginate'
gem 'yajl-ruby'

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'rspec-rails'
end
